apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gq7ke0dng-nodejs
  janus-idp.io/tekton: gq7ke0dng-nodejs
  backstage.io/kubernetes-id: gq7ke0dng-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gq7ke0dng-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
