apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gq7ke0dng-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gq7ke0dng-nodejs 
  name: gq7ke0dng-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gq7ke0dng-nodejs 
